# Generated by Django 3.1 on 2020-08-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('center_name', models.CharField(max_length=30)),
                ('region_code', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('date_of_join', models.DateField()),
                ('salary', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
